version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/backend"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "ejdbwhebdchwebchw"
    reviewers:
      - "ejdbwhebdchwebchw"
    allow:
      - dependency-type: "all"
    automerge: true
    automerge-type: "pr"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "deps"
      include: "scope"
    labels:
      - "dependencies"
      - "security"
    assignees:
      - "ejdbwhebdchwebchw"
    reviewers:
      - "ejdbwhebdchwebchw"
    allow:
      - dependency-type: "all"
    automerge: true
    automerge-type: "pr"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    labels:
      - "github-actions"
      - "security"
    assignees:
      - "ejdbwhebdchwebchw"
    reviewers:
      - "ejdbwhebdchwebchw"
    automerge: true
    automerge-type: "pr"

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "daily"
      time: "02:00"
      timezone: "Etc/UTC"
    open-pull-requests-limit: 10
    labels:
      - "docker"
      - "security"
    assignees:
      - "ejdbwhebdchwebchw"
    reviewers:
      - "ejdbwhebdchwebchw"
    automerge: true
    automerge-type: "pr"
